export { StockPage } from './pages/StockPage'
export { MovementsJournalPage } from './pages/MovementsJournalPage'
export { StockEntriesPage } from './pages/StockEntriesPage'
export { StockEntryDetailPage } from './pages/StockEntryDetailPage'
export { StockExitsPage } from './pages/StockExitsPage'
export { StockExitDetailPage } from './pages/StockExitDetailPage'
export { CustomerReturnsPage, SupplierReturnsPage } from './pages/ReturnsPage'
